# Generated by Django 6.0.7 on 2026-09-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=100)),
                ('numero_estabelecimento', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id_loja', models.AutoField(primary_key=True, serialize=False)),
                ('nome_loja', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone_loja', models.CharField(blank=True, max_length=15, null=True)),
                ('email_loja', models.EmailField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('foto_estabelecimento', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.categoria')),
                ('id_endereco', models.ForeignKey(db_column='id_endereco', on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.categoria')),
                ('id_loja', models.ForeignKey(db_column='id_loja', on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('nome_servico', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('id_loja', models.ForeignKey(db_column='id_loja', on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('id_tipo_usuario', models.ForeignKey(db_column='id_tipo_usuario', on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('id_loja', models.ForeignKey(blank=True, db_column='id_loja', null=True, on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.loja')),
                ('id_produto', models.ForeignKey(blank=True, db_column='id_produto', null=True, on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.produto')),
                ('id_servico', models.ForeignKey(blank=True, db_column='id_servico', null=True, on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.servico')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LojaFavoritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_loja', models.ForeignKey(db_column='id_loja', on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.loja')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.usuario')),
            ],
            options={
                'unique_together': {('id_usuario', 'id_loja')},
            },
        ),
    ]
