# Generated by Django 6.0.7 on 2026-09-11 03:30

from django.db import migrations

    
CATEGORIAS = [
    "Alimentos", "Moda", "Esportes", "Construção", "Saúde",
    "Pets", "Ambiente", "Tecnologia", "Beleza", "Outros"
]
    
def criar_categorias(apps, schema_editor):
    Categoria = apps.get_model('AppStoreLink', 'Categoria')
    for nome in CATEGORIAS:
        Categoria.objects.get_or_create(tipo_categoria=nome)
                
def remover_categoria(apps, schema_editor):
    Categoria = apps.get_model('AppStoreLink', 'Categoria')
    Categoria.objects.filter(tipo_categoria__in=CATEGORIAS).delete()        
        
class Migration(migrations.Migration):
    dependencies = [
        ('AppStoreLink', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_categorias, remover_categoria),
    ]

