# Generated by Django 6.0.7 on 2026-09-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppStoreLink', '0002_popular_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='categoria',
        ),
    ]
