# Generated by Django 6.0.7 on 2026-09-25 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppStoreLink', '0003_remover_categoria_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='nome_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_tipo_usuario',
            field=models.ForeignKey(blank=True, db_column='id_tipo_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='AppStoreLink.tipousuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
